// src/model/OrderStatus/order-status.enum.ts
export enum OrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  DEPOSIT_PENDING = 'DEPOSIT_PENDING',
  DEPOSIT_PAID = 'DEPOSIT_PAID',
  MANUFACTURING = 'MANUFACTURING',
  READY = 'READY'
}