name: gohan_medic_mobile
description: Application mobile pour Gohan Medic
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.2
  google_fonts: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Retirons temporairement la section assets puisque nous utilisons une icône
  # assets:
  #   - assets/images/logo.png

# Assurez-vous que cette section est correctement indentée 