name: gohanmedic_flutterprojetmobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  webview_flutter: ^4.4.4
  flutter_paypal: ^0.2.1
  file_picker: ^8.0.0
  http: ^1.3.0
  http_parser: ^4.0.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  uni_links: ^0.5.1
  image_picker: ^1.1.2 # ✅ Version unique
  flutter_image_compress: ^2.1.0 # ✅ Optimisation des images avant upload

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.2 # ✅ Évite les conflits de versions

flutter:
  uses-material-design: true

  assets:
    - assets/image/logogohanmedic.png
    - assets/image/defautproduit.png
    - assets/uploads/default.jpg

